MvcHamburgerci/Areas/Admin/Controllers/MalzemeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcHamburgerci.Data;
using MvcHamburgerci.Entities;
using MvcHamburgerci.Models;

namespace MvcHamburgerci.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class MalzemeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public MalzemeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View(_db.EkstraMalzemeler.ToList());
        }

        public IActionResult Yeni()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Yeni(MalzemeViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var malzeme = new EkstraMalzeme();
                malzeme.Ad = vm.Ad;
                malzeme.Fiyat = (decimal)vm.Fiyat;
                _db.EkstraMalzemeler.Add(malzeme);
                _db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View();
        }

        public IActionResult Duzenle(int id)
        {
            EkstraMalzeme? malzeme = _db.EkstraMalzemeler.Find(id);
            var vm = new MalzemeViewModel();
            vm.Ad = malzeme.Ad;
            vm.Fiyat = malzeme.Fiyat;
            TempData["Id"] = id;
            return View(vm);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Duzenle(MenuViewModel vm)
        {
            EkstraMalzeme? malzeme = _db.EkstraMalzemeler.Find(TempData["Id"]);
            malzeme.Ad = vm.Ad;
            malzeme.Fiyat = (decimal)vm.Fiyat;

            _db.Update(malzeme);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
        public IActionResult Sil(int id)
        {
            EkstraMalzeme? malzeme = _db.EkstraMalzemeler.Find(id);
            if (malzeme == null) return NotFound();

            return View(malzeme);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SilOnay(int id)
        {
            EkstraMalzeme? malzeme = _db.EkstraMalzemeler.Find(id);
            if (malzeme == null)
                return NotFound();

            _db.Remove(malzeme);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcHamburgerci/Areas/Admin/Controllers/MenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcHamburgerci.Data;
using MvcHamburgerci.Entities;
using MvcHamburgerci.Models;
using System.Data;

namespace MvcHamburgerci.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class MenuController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _env;

        public MenuController(ApplicationDbContext db, IWebHostEnvironment env)
        {
            _db = db;
            _env = env;
        }
        public IActionResult Index()
        {
            return View(_db.Menuler.ToList());
        }

        public IActionResult Yeni()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Yeni(MenuViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var menu = new Menu();
                if (vm.Resim != null)
                {
                    string dosyaAd = Guid.NewGuid().ToString() + Path.GetExtension(vm.Resim.FileName);
                    string kayitYolu = Path.Combine(_env.WebRootPath, "img", dosyaAd);
                    using (var stream = new FileStream(kayitYolu, FileMode.Create))
                    {
                        vm.Resim.CopyTo(stream);
                    }

                    menu.DosyaAd = dosyaAd;
                }

                menu.Ad = vm.Ad;
                menu.Fiyat = (decimal)vm.Fiyat;
                _db.Menuler.Add(menu);
                _db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View();
        }

        public IActionResult Duzenle(int id)
        {
            Menu? menu = _db.Menuler.Find(id);
            var vm = new MenuViewModel();
            vm.Ad = menu.Ad;
            vm.Fiyat = menu.Fiyat;
            TempData["Id"] = id;
            return View(vm);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Duzenle(MenuViewModel vm)
        {
            Menu menu = _db.Menuler.Find(TempData["Id"]);
            menu.Ad = vm.Ad;
            menu.Fiyat = (decimal)vm.Fiyat;

            if (vm.Resim != null)
            {
                string dosyaAd = Guid.NewGuid().ToString() + Path.GetExtension(vm.Resim.FileName);
                string kayitYolu = Path.Combine(_env.WebRootPath, "img", dosyaAd);
                using (var stream = new FileStream(kayitYolu, FileMode.Create))
                {
                    vm.Resim.CopyTo(stream);
                }

                menu.DosyaAd = dosyaAd;
            }

            _db.Update(menu);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
        public IActionResult Sil(int id)
        {
            Menu menu = _db.Menuler.Find(id);
            if (menu == null) return NotFound();

            return View(menu);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SilOnay(int id)
        {
            Menu? menu = _db.Menuler.Find(id);
            if (menu == null)
                return NotFound();
            if (menu.DosyaAd != null)
            {
                string dosyaYolu = Path.Combine(_env.WebRootPath, "img", menu.DosyaAd);
                if (System.IO.File.Exists(dosyaYolu))
                    System.IO.File.Delete(dosyaYolu);
            }
            _db.Remove(menu);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcHamburgerci/Areas/Admin/Controllers/YoneticiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcHamburgerci.Data;
using System.Data;

namespace MvcHamburgerci.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class YoneticiController : Controller
    {
        private readonly ApplicationDbContext _db;

        public YoneticiController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult KullaniciSiparisleri()
        {
            return View(_db.Siparisler.Include(s => s.SeciliMenusu).Include(s => s.Kullanici).ToList());
        }
    }
}

MvcHamburgerci/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Yönetici Paneli</title>
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <link href="~/admin/css/styles.css" rel="stylesheet" />
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand text-white fs-4 fw-bold" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="~/img/logo.png" width="50px" alt="" />
            OzBurger
        </a>
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <div class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                <button type="submit" class="nav-link btn btn-link text-white fw-bold"><i class="fa-solid fa-user me-2"></i>Çıkış Yap</button>
            </form>
            </div>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Başlangıç</div>
                            <a class="nav-link" asp-area="Admin" asp-action="Index" asp-controller="Yonetici">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Yönetici Paneli
                            </a>
                            <div class="sb-sidenav-menu-heading">Yetkiler</div>
                            <a class="nav-link" asp-action="Index" asp-controller="Menu" asp-area="Admin">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Menüler
                            </a>
                            <a class="nav-link" asp-action="Index" asp-controller="Malzeme" asp-area="Admin">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Ekstra Malzelemeler
                            </a>
                        <a class="nav-link" asp-action="KullaniciSiparisleri" asp-controller="Yonetici" asp-area="Admin">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Siparişler
                        </a>

                        
                            
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Giriş Yapan:</div>
                            Admin
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    @RenderBody()
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Tüm hakları saklıdır &copy; @DateTime.Now.Year</div>
                            <div>
                                <a href="#">Gizlilik Politikası</a>
                                &middot;
                                <a href="#">Şartlar &amp; Koşullar</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="~/admin/js/scripts.js"></script>
        <a href="~/lib/bootstrap/dist/js/bootstrap.bundle.js.map">~/lib/bootstrap/dist/js/bootstrap.bundle.js.map</a>
        <a href="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js.map">~/lib/bootstrap/dist/js/bootstrap.bundle.min.js.map</a>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        
    </body>
</html>